trigger:
  branches:
    include:
      - main

parameters:
  - name: virtualMachineName
    type: string
    default: 'gpatinovm01'

  - name: virtualMachineSize
    type: string
    default: 'Standard_B2s'

pool:
  name: Default

variables:
  resourceGroupName: 'gpatinorg01'
  deploymentName: 'GPvmDeployment'

jobs:
- job: DeployBicep
  displayName: 'Deploy Azure VM using Bicep'
  steps:

  - checkout: self

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'GPServiceConnection'
      KeyVaultName: 'gpatino-kv2'
      SecretsFilter: 'adminID,adminPassword'
      RunAsPreJob: true

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'GPServiceConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Deploying Bicep template..."
        az deployment group create \
          --name $(deploymentName) \
          --resource-group $(resourceGroupName) \
          --template-file ./gpvm1.bicep \
          --parameters \
            vmName='${{ parameters.virtualMachineName }}' \
            vmSize='${{ parameters.virtualMachineSize }}' \
            adminUsername='$(adminID)' \
            adminPassword='$(adminPassword)'
